### ISSUE TITLE
not working as intended

### ISSUE THREAD

**Issue by Mrfalk** [ropellanda/Joymap-minimal#1]
so i tried it out a fresh retropie 4.8 image
And none off the orignal futures was working.
no joycon connection screen.
no player selction screen.
and no kodi,debian,terminal screen selection,

booted straight in to emulationstation and joycons wont even register or connect.

followed cfoote7 installation guide with your github pull but still now working as intended in his videos

awesome that you did this and awesome work but i cant get anything to work as shown in his videos and descriptions

**Comment by ropellanda** [comment]
That's odd, did you install the Pixel desktop environment on top of RetroPie?
The connection screen is still there, but it unfortunately can’t run on headless.
Try RetroPie-Setup > configuration/tools > raspbiantools > install pixel desktop environment, if you haven’t already.

**Comment by Mrfalk** [comment]
im talking about this pairing mode for joycons as seen here
https://www.youtube.com/watch?v=qiDA6RoLeo0&t=22s
and the selection screen for each indivual port seen here
https://www.youtube.com/watch?v=qiDA6RoLeo0&t=44s
thats what im trying to get to work =)

**Comment by ropellanda** [comment]
You need to have the desktop environment installed in order for the connection screen to work, it unfortunately can’t run without X11.

**Comment by Mrfalk** [comment]
all right ill give everything another try keep you posted

**Comment by ropellanda** [comment]
Ok, thanks, I'll try recompiling it on a clean image to see if I can reproduce your issue

**Comment by Mrfalk** [comment]
I was working on it yesterday and got most off it working. The joycon
pairing was showing up and connection joycon was working from time to time.
But the OS selection screen dident show and installed pixel and kodi before
i used your git code.

**Comment by ropellanda** [comment]
Installing the original script should fix that:
``` 
wget https://raw.githubusercontent.com/cfoote7/PiSwitch/master/NewTouchBoot/pywx.py
sudo cp pywx.py /opt/retropie/configs/all/NewTouchBoot
```

**Comment by ropellanda** [comment]
Hi, did it all work out for you?
